### ISSUE TITLE
instrument "hanging" and pressing stdout/stderr forces re-login

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#168] opened 2017-09-21 10:24 UTC
I was testing this VE which Mads reported was really slow on mcweb (but takes a few minutes on my dualcore)
![screenshot from 2017-09-21 12-21-00](https://user-images.githubusercontent.com/15801156/30691243-702af2b4-9ec7-11e7-9a86-4044e302a86b.png)
It has run for half an hour now on mcweb so something is wrong
https://sim.e-neutrons.org/simrun/3031
however when I press stderr or stdout to figure out what is going on I am forced to relogin (even though I am still logeed in according to the instrument interface window).
![screenshot from 2017-09-21 12-25-50](https://user-images.githubusercontent.com/15801156/30691460-13b27830-9ec8-11e7-9e3e-29de8c5f8a34.png)

 And even after relogin I am still forced to re-login once again when I press stderr/stderr and I never see the output.

**Comment by willend** [comment] 2017-09-21 11:24
It seems the McWeb "worker" process had crashed, as a matter of fact no simulations were running.

I have restarted a simulation ala your Ni_TAS above that went through OK - see http://sim.e-neutrons.org/static/data/mcstas_Ni_TAS_20170921_111921/browse.html

And even your work is now completed, see http://sim.e-neutrons.org/static/data/udby_Ni_TAS_20170921_095815/browse.html!

I don't know exactly what was going on, let us know if it occurs again

**Comment by lindaudby** [comment] 2017-09-21 13:17
Will do!
The specific simulation is however still slower on mcweb than my dualcore. Can we somehow figure out if the threading works properly on mcweb?

**Comment by willend** [comment] 2017-09-21 18:06
Please quantify "slower"? :-) e-neutrons.org is running on a ~10 year old 16-core Dell Intel(R) Xeon(R) CPU X7350  @ 2.93GHz, but every simulation job there is (currently) allowed to consume 4 cores... So you shouldn't expect your simulations to run much faster there than on your pretty new laptop... 

If you by "threading" mean MPI parallelisation, these things either "work" or "don't work". And in this case everything looks fine as the text **This instrument has been compiled with MPI support.**  occurs below :

<pre>
pkwi@mcstas-01:~$ /srv/mcweb/McWeb/mcsimrunner/sim/swedness/Ni_TAS.out --help
templateTAS (Ni_TAS.instr) instrument simulation, generated with McStas 2.3 - Apr. 06, 2016 (Apr. 06, 2016)
Usage: /srv/mcweb/McWeb/mcsimrunner/sim/swedness/Ni_TAS.out [options] [parm=value ...]
Options are:
  -s SEED   --seed=SEED      Set random seed (must be != 0)
  -n COUNT  --ncount=COUNT   Set number of neutrons to simulate.
  -d DIR    --dir=DIR        Put all data files in directory DIR.
  -t        --trace          Enable trace of neutrons through instrument.
  -g        --gravitation    Enable gravitation for all trajectories.
  --no-output-files          Do not write any data files.
  -h        --help           Show this help message.
  -i        --info           Detailed instrument information.
  --format=FORMAT            Output data files using FORMAT=MCSTAS

This instrument has been compiled with MPI support.
  Use 'mpirun /srv/mcweb/McWeb/mcsimrunner/sim/swedness/Ni_TAS.out [options] [parm=value ...]'.
Instrument parameters are:
  EI              (double) [default='40']
  EF              (double) [default='40']
  QHK             (double) [default='1']
  QL              (double) [default='1']
  Temperature_K   (double) [default='70']
Known signals are: USR1 (status) USR2 (save) TERM (save and exit)
</pre>

**Comment by willend** [comment] 2017-09-21 18:08
@climbcat a question: is there a "maximum" number of worker threads/slaves running at once?

(Just want to dimension the MPI cores / worker process properly to the number of available cores...)

**Comment by willend** [comment] 2017-09-26 09:12
@lindaudby we have increased the mpi parallelisation to "full", i.e. 16 cores pr. simulation - so as long as you are "alone" simulating, this will run as fast as the machine possibly can.

(The issue is of course that once more simulations run, they will equally "share" the resources - so not ideal for running "classroom" courses I guess - but these also ought to run in Munich IMHO)

**Comment by lindaudby** [comment] 2017-09-26 11:23
OK, thanks :)
We may also want to consider finding some money to buy new hardware for the e-neutrons test server is you say it is 10y old.

**Comment by lindaudby** [comment] 2017-09-28 13:53
OK, thanks :)
We may also want to consider finding some money to buy new hardware for the e-neutrons test server is you say it is 10y old.

**Comment by lindaudby** [comment] 2017-09-28 13:54
It just happened again - the forced relogin pressing stdout in this simulation: https://sim.e-neutrons.org/simrun/3056

**Comment by climbcat** [comment] 2017-09-28 14:19
Hi. I have restarted the worker process, which had again crashed somehow. Peter, I wonder what this means? It looks like our script isn't working as it should?

@mcstas-01:/srv/mcweb/McWeb/mcsimrunner$ sudo /etc/init.d/uwsgi_mcweb restart
[....] Stopping system uwsgi_mcweb daemon:start-stop-daemon: warning: failed to kill 26046: No such process
No process in pidfile '/var/run/mcweb-worker' found running; none killed.
 failed!
[ ok ] Starting system uwsgi_mcweb daemon:.

**Comment by willend** [comment] 2017-10-03 13:10
We have now implemented that as soon as the simulation "worker" process has actually started (but the simulation not yet ended), one will get output like this:

![firefoxscreensnapz001](https://user-images.githubusercontent.com/8593355/31126629-aa5a8952-a84c-11e7-80c6-36eb83539024.png)

If on the other hand the worker did NOT (yet or at all) start, one will (as usual) get the "login" page, as this is a redirect one gets the moment the "file" stdout.txt or stderr.txt don't exist. There is no reason to attempt logging in, simply wait a little longer and try again. I cases where redirects to the "login" page keeps coming, it is now simply the signature of a crashed worker process - which is something only @climbcat or I can handle anyway...

**Comment by lindaudby** [comment] 2017-10-18 09:47
OK, according to your description above it seems the worker process has crashed 
https://sim.e-neutrons.org/simrun/3071

**Comment by willend** [comment] 2017-11-23 13:12
Nope, the job seems to have ended - there are now data in the stdout and stderr links... But the plotting must have failed. Anyway, hard to debug that retrospectively. Let's look if something occurs again.

Closing

**Closed by willend** 2017-11-23 13:12 UTC
