### ISSUE TITLE
Simrunner: Show list of all instruments

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#63] opened 2016-01-05 12:59 UTC
It would be better if the instrument menu (the one that shows groups of instruments) was available from http://sim.e-neutrons.org/instrument-menu and not only if a particular instrument is specified e.g. http://sim.e-neutrons.org/instrument-menu/imaging which is counter-intuitive and thus complicates it for us to construct learning paths in the courses.

It would also be nice if all instruments in the McStas distro were available as a groups from this menu grouped as they are in mcgui by sites.

**Comment by lindaudby** [comment] 2016-01-05 13:03
related to #58

**Comment by willend** [comment] 2016-01-05 13:04
The first bit about http://sim.e-neutrons.org/instrument-menu is indeed a kind of duplicate of https://github.com/McStasMcXtrace/McWeb/issues/58. 

To keep things simple (KISS) I suggest that the first (alphabetically) group is picked if nothing is chosen, similarly that the first instrument (alphabetically) is picked if nothing is chosen, i.e.

http://sim.e-neutrons.org/instrument-menu/PSI will go to http://sim.e-neutrons.org/instrument-menu/PSI/PSI_DMC and http://sim.e-neutrons.org/instrument-menu/ will go to http://sim.e-neutrons.org/instrument-menu/Agroup/Aninstrument

**Comment by willend** [comment] 2016-01-05 13:22
On the other hand I feel that this is nice-to-have rather than need-to-have and time is short, so marking this post release, sorry :-)

**Closed** 2017-04-10 06:41 UTC
Labels: Jakob/Peter, Post release
