### ISSUE TITLE
Bad gateway 502 periodic error

### ISSUE THREAD

**Issue by mads-bertelsen** [McStasMcXtrace/McWeb#162] opened 2017-09-15 06:30 UTC
When testing quizzes during the Tartu NNSP SwedNESS summerschool, the quizes frequently produced the error: "Bad gateway 502" when checking an answer, trying to progress to the next page and so on. Initially the error only occurred when all students were doing the quiz, so I assumed it was related to load on the server. This morning however it occurred in every question of the SANS I quiz during a lecture where I presumably was the only one using the system.

**Comment by willend** [comment] 2017-09-15 06:58
Hi @mads-bertelsen and @lindaudby, I am almost 100% sure this is a duplicate of
https://github.com/McStasMcXtrace/McWeb/issues/152 - and currently there is no other solution than to reimplement the quizzes - which is on Linda's table.

The issue is that we are running an unsupported question type called qtype_algebra (doesn't run with recent moodle versions) - the log is full of warnings like these:
<pre>
PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; qtype_algebra_parser_nullterm has a deprecated constructor in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 422
PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; qtype_algebra_parser_number has a deprecated constructor in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 473
PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; qtype_algebra_parser_variable has a deprecated constructor in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 590
PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; qtype_algebra_parser_power has a deprecated constructor in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 753
PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; qtype_algebra_parser_divide has a deprecated constructor in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 800
PHP message: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; qtype_algebra_parser_multiply has a deprecated constructor in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 855
</pre>

**Comment by willend** [comment] 2017-09-15 07:19
As attempted for #152 I have tried reinstalling the qtype_algebra class - which seems to have momentarily improved the situation...  But I am also convinced this will come back

**Comment by mads-bertelsen** [comment] 2017-09-15 07:34
Earlier this only happened when checking answers and similar, in this instance it happened even when going to the next page in the quiz. I thought this would provide more information on the issue, but didn't see the previous topic.

**Comment by lindaudby** [comment] 2017-09-15 07:35
OK, if you can patch it like that if the error occurs again during the next week of the Tartu school I will take a look at converting all the qtype_algebra questions into something else. But it is quite a big task.

**Comment by willend** [comment] 2017-09-15 07:45
I know it is a big task @lindaudby, but there is no way around it it seems - see below...

I've posted a question about support for moodle 3.3 at the plugin page
(https://moodle.org/plugins/qtype_algebra)

![safariscreensnapz034](https://user-images.githubusercontent.com/8593355/30471283-74aba9ec-99f8-11e7-9a5a-087d42f6589c.png)

- But I guess the answer is a clean "no", since the page is saying

![safariscreensnapz035](https://user-images.githubusercontent.com/8593355/30471840-77cba580-99fa-11e7-9599-6377402f92cd.png)

- Unmaintained code, the solution is to walk away and don't look back

**Comment by willend** [comment] 2017-09-15 07:47
And I **can not** be on "urgent call" during all of next week to randomly try reinstalling, as we have no proof that this is really "working".

What I could do is to hack in a (hourly?) cronjob that does this reinstall "all the time", but that has a good chance of having other side effects.

**Comment by lindaudby** [comment] 2017-09-15 08:45
OK, please try the cronjob hack. 

And as I said I will remake the content as soon as possible to not use the algebra question type. But we are talking 10 quiz questions implemented in 4 courses so it is several full days of work and I cannot do it on top of servicing the running course which is already making me work overtime.

**Comment by willend** [comment] 2017-09-15 09:09
cron-hack in place... Have no idea if this will help or not, but every 5 minutes past the hour, qtype_algebra is reinstalled - status page for control:
https://sim.e-neutrons.org/static/qtype_algebra_status.html

**Comment by willend** [comment] 2017-10-03 12:36
@lindaudby I guess we could close this one if there is a related content-issue in place?

**Comment by willend** [comment] 2017-10-03 13:15
Oh yes, here it was https://github.com/McStasMcXtrace/McWeb/issues/152

**Closed by willend** 2017-10-03 13:15 UTC
Labels: content
