### ISSUE TITLE
mcweb user manage

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#135] opened 2017-09-06 15:48 UTC
I can't see the full password (text extends frame)
Using FIrefox

**Comment by climbcat** [comment] 2017-09-06 16:29
Hi, thanks for this, it should be fixed. You can still double-click on the password. P.S. please do not post passwords online :-) 

BR

**Comment by willend** [comment] 2017-09-06 17:01
Suggestion for the fix: 

If the right side (data table) of the HTML table is allowed to have "any width" (i.e. not restricted to ~80% or similar), i believe that we will automatically get a scrollbar?

(In any case, the problem is mainly related to long email addrs/usernames, which we don't have on elearn1)

**Comment by lindaudby** [comment] 2017-09-06 18:42
Argh yes, sorry about the screendump content - was too eager to document the problem.
Still doesn't work in Firefox (55.0.2 Ubuntu) but ok in Chrome.

**Comment by climbcat** [comment] 2017-09-08 10:16
We should do a layout-overhaul soon and have a look at a few things.

**Comment by lindaudby** [comment] 2017-09-14 15:41
stepping down priority since I can see the full pass in chrome (which I normally don't use)

**Comment by climbcat** [comment] 2017-09-19 14:44
Fixed be completely removing /manage pages width limit.

**Closed by climbcat** 2017-09-19 14:44 UTC
Labels: bug, Priority 700
