### ISSUE TITLE
cronjob - send contact item text email to admin

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McWeb#97] opened 2016-11-17 14:22 UTC

**Comment by willend** [comment] 2017-09-06 17:44
- Essentially: Provide info on how many signups are open, plus the email adresses

**Comment by willend** [comment] 2017-09-06 17:46
I believe this is a duplicate of https://github.com/McStasMcXtrace/McWeb/issues/93

**Closed by willend** 2017-09-06 17:46 UTC
Labels: enhancement
